version: '3.8'

services:
  discord-bot:
    build: .
    command: python main.py
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SERVER_IP=${SERVER_IP}
    env_file:
      - .env
